# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: activemessaging 0.13.0 ruby lib

Gem::Specification.new do |s|
  s.name = "activemessaging"
  s.version = "0.13.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Tirsen", "Andrew Kuklewicz", "Olle Jonsson", "Sylvain Perez", "Cliff Moon", "Uwe Kubosch", "Lance Cooper", "Matt Campbell"]
  s.date = "2014-06-18"
  s.description = "ActiveMessaging is an attempt to bring the simplicity and elegance of rails development to the world of messaging. Messaging, (or event-driven architecture) is widely used for enterprise integration, with frameworks such as Java's JMS, and products such as ActiveMQ, Tibco, IBM MQSeries, etc. Now supporting Rails 3 as of version 0.8.0."
  s.email = "activemessaging-discuss@googlegroups.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Appraisals",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "activemessaging.gemspec",
    "gemfiles/activesupport23.gemfile",
    "gemfiles/activesupport23.gemfile.lock",
    "gemfiles/activesupport30.gemfile",
    "gemfiles/activesupport30.gemfile.lock",
    "gemfiles/activesupport31.gemfile",
    "gemfiles/activesupport31.gemfile.lock",
    "gemfiles/activesupport32.gemfile",
    "gemfiles/activesupport32.gemfile.lock",
    "generators/a13g_test_harness/a13g_test_harness_generator.rb",
    "generators/a13g_test_harness/templates/active_messaging_test.rhtml",
    "generators/a13g_test_harness/templates/active_messaging_test_controller.rb",
    "generators/a13g_test_harness/templates/index.rhtml",
    "generators/filter/USAGE",
    "generators/filter/filter_generator.rb",
    "generators/filter/templates/filter.rb",
    "generators/filter/templates/filter_test.rb",
    "generators/processor/USAGE",
    "generators/processor/processor_generator.rb",
    "generators/processor/templates/application_processor.rb",
    "generators/processor/templates/broker.yml",
    "generators/processor/templates/jruby_poller",
    "generators/processor/templates/messaging.rb",
    "generators/processor/templates/poller",
    "generators/processor/templates/poller.rb",
    "generators/processor/templates/processor.rb",
    "generators/processor/templates/processor_test.rb",
    "generators/tracer/USAGE",
    "generators/tracer/templates/controller.rb",
    "generators/tracer/templates/helper.rb",
    "generators/tracer/templates/index.rhtml",
    "generators/tracer/templates/layout.rhtml",
    "generators/tracer/templates/trace_processor.rb",
    "generators/tracer/tracer_generator.rb",
    "init.rb",
    "lib/activemessaging.rb",
    "lib/activemessaging/adapter.rb",
    "lib/activemessaging/adapters/amqp.rb",
    "lib/activemessaging/adapters/asqs.rb",
    "lib/activemessaging/adapters/base.rb",
    "lib/activemessaging/adapters/beanstalk.rb",
    "lib/activemessaging/adapters/jms.rb",
    "lib/activemessaging/adapters/reliable_msg.rb",
    "lib/activemessaging/adapters/stomp.rb",
    "lib/activemessaging/adapters/synch.rb",
    "lib/activemessaging/adapters/test.rb",
    "lib/activemessaging/adapters/wmq.rb",
    "lib/activemessaging/base_message.rb",
    "lib/activemessaging/filter.rb",
    "lib/activemessaging/gateway.rb",
    "lib/activemessaging/message_sender.rb",
    "lib/activemessaging/named_base.rb",
    "lib/activemessaging/processor.rb",
    "lib/activemessaging/railtie.rb",
    "lib/activemessaging/test_helper.rb",
    "lib/activemessaging/threaded_poller.rb",
    "lib/activemessaging/trace_filter.rb",
    "lib/generators/active_messaging/install/USAGE",
    "lib/generators/active_messaging/install/install_generator.rb",
    "lib/generators/active_messaging/install/templates/application_processor.rb",
    "lib/generators/active_messaging/install/templates/broker.yml",
    "lib/generators/active_messaging/install/templates/poller",
    "lib/generators/active_messaging/install/templates/poller.rb",
    "lib/generators/active_messaging/install/templates/threaded_poller",
    "lib/generators/active_messaging/processor/USAGE",
    "lib/generators/active_messaging/processor/processor_generator.rb",
    "lib/generators/active_messaging/processor/templates/messaging.rb",
    "lib/generators/active_messaging/processor/templates/processor.rb",
    "lib/generators/active_messaging/processor/templates/processor_spec.rb",
    "lib/generators/active_messaging/processor/templates/processor_test.rb",
    "lib/tasks/start_consumers.rake",
    "poller.rb",
    "test/all_tests.rb",
    "test/app/config/broker.yml",
    "test/asqs_test.rb",
    "test/config_test.rb",
    "test/filter_test.rb",
    "test/gateway_test.rb",
    "test/jms_test.rb",
    "test/reliable_msg_test.rb",
    "test/stomp_test.rb",
    "test/test_helper.rb",
    "test/tracer_test.rb"
  ]
  s.homepage = "http://github.com/kookster/activemessaging"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Official activemessaging gem, now hosted on github.com/kookster. (kookster prefix temporary)"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.11"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<stomp>, [">= 0"])
      s.add_development_dependency(%q<appraisal>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.11"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<stomp>, [">= 0"])
      s.add_dependency(%q<appraisal>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.11"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<stomp>, [">= 0"])
    s.add_dependency(%q<appraisal>, [">= 0"])
  end
end

